### ISSUE TITLE
ADB error on Mac

### ISSUE THREAD

**Issue by clayrisser** [clayrisser/reactant#5]
I get the following error when running `npm run start:android` on mac.

```
reaction start -p android

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn adb ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shirt-chair-mobile@0.1.0 start:android: `reaction start -p android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shirt-chair-mobile@0.1.0 start:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by clayrisser** [comment]
This error has disappeared with updates to Android.
